//-----------------------------------------------------------------------------
// piwi, 2018
//
// This code is licensed to you under the terms of the GNU GPL, version 2 or,
// at your option, any later version. See the LICENSE.txt file for the text of
// the license.
//-----------------------------------------------------------------------------
// Version information on fpga images
//
// This file is generated by fpga_compress. Don't edit!
//-----------------------------------------------------------------------------


const int fpga_bitstream_num = 2;
const char* const fpga_version_information[2] = {
	"fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04",
	"fpga_hf.bit built for 2s30vq100 on 2019/03/20 at 08:08:07"
};
